# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 847cecc79c7283954f0903f4abe6200f7639f151cd2039367a03d308b36ea5f8fa6f552eab9fc8104e8931983b3620ec236d92d3974232313f5c08dd95decbdf

test:
  secret_key_base: 4bcdbdfede6925628f2e6ccac009a904e63cdd5232137af9eaae2432a61c79e2c305772d251d1aa4a3ce533c3c63f0bf1e24e2fe81838382e89274e2acf9138e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
